# Generated by Django 3.2.8 on 2021-10-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('second_name', models.CharField(blank=True, max_length=64, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not started', 'Not started'), ('in progress', 'In progress'), ('postponed', 'Postponed'), ('finished', 'Finished'), ('failed', 'Failed')], default='not started', max_length=64)),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('direction', models.ManyToManyField(to='userprofile.Direction')),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userskillprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.user')),
            ],
        ),
    ]
