version: "3"

services:

  postgres:
    image: postgres:12
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myskills
      - POSTGRES_USER=myskills
      - POSTGRES_PASSWORD=myskills

  web-app:
    build: .
    environment:
      DB_CONN_URI: psycopg2+postgresql://myskills:myskills@postgres:5432/myskills
    command: >
      sh -c "python myskills/manage.py migrate &&
             python myskills/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - postgres


