# Generated by Django 3.2.8 on 2021-10-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userskillprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.userinfo'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
