version: "3"

services:
  web-app: &web-app-config
    build:
      context: .
    command: flask run --host=0.0.0.0
#    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      DB_CONN_URI: postgresql+psycopg2://user:password@pg:5432/books
      FLASK_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - pg

  web-app-prod:
    <<: *web-app-config
    environment:
      DB_CONN_URI: postgresql+psycopg2://user:password@pg:5432/books
      FLASK_ENV: production

  pg:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=books
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready books -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

